Read_Target_Material – quarantine
Read_Target_Material Subroutine
42 statements
Source File
public subroutine Read_Target_Material(LU, Binary, D)
This subroutine is for the Target_Material derived type data read
LU - The logical unit for input Binary - Flag for binary or ASCII input D - The data to pass back and is of type Target_Material
Make sure the Z_Target_Material_p pointer is not associated
Make sure the D_Target_Material_p pointer is not associated
Read the file to get the Name, Num_Isotopes, and Density
Allocate Arrays
Read the data
Return to calling programs
End of Subroutine
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: LU
logical, intent(in) :: Binary
type(Target_Material_Pointer), intent(out) :: D
Local Varaibles IOSTAT - THe status of he IO statement IOMSG - The associate message with an error in the IO statement i - do loop variable
Called by
Contents
Source Code
Read_Target_Material
Source Code
    Subroutine Read_Target_Material ( LU, Binary, D )
!
!**********************************************************************************************************************************
! This subroutine is for the Target_Material derived type data read
!**********************************************************************************************************************************
!
        Implicit None
!
!**********************************************************************************************************************************
! LU - The logical unit for input
! Binary - Flag for binary or ASCII input
! D - The data to pass back and is of type Target_Material
!**********************************************************************************************************************************
!
        Integer, intent(in) :: LU
        Logical, intent(in) :: Binary
        Type ( Target_Material_Pointer ), intent(out) :: D
!
!**********************************************************************************************************************************
! Local Varaibles
!   IOSTAT - THe status of he IO statement
!   IOMSG - The associate message with an error in the IO statement
!   i - do loop variable
!**********************************************************************************************************************************
!
        Integer :: IOSTAT, i
        Character(Len=IOMSG_SIZE) :: IOMSG
!
!**********************************************************************************************************************************
! Make sure the A_Target_Material_p pointer is not associated
!**********************************************************************************************************************************
!
DMAlc1: If (Associated (D%A_Target_Material_p)) Then
            Write (*,'(a)') 'A_Target_Material_p already Associated - nullify'
            Nullify ( D%A_Target_Material_p )
        End If DMAlc1
!
!**********************************************************************************************************************************
! Make sure the Z_Target_Material_p pointer is not associated
!**********************************************************************************************************************************
!
DMAlc2: If (Associated (D%Z_Target_Material_p)) Then
            Write (*,'(a)') 'Z_Target_Material_p already Associated - nullify'
            Nullify ( D%Z_Target_Material_p )
        End If DMAlc2
!
!**********************************************************************************************************************************
! Make sure the D_Target_Material_p pointer is not associated
!**********************************************************************************************************************************
!
DMAlc3: If (Associated (D%D_Target_Material_p)) Then
            Write (*,'(a)') 'D_Target_Material_p already Associated - nullify'
            Nullify ( D%D_Target_Material_p )
        End If DMAlc3
!
!**********************************************************************************************************************************
! Read the file to get the Name, Num_Isotopes, and Density
!**********************************************************************************************************************************
!
bin1:   If (Binary) Then
            Read ( unit=LU,        iostat=IOSTAT, iomsg=IOMSG ) D%Name, D%Num_Isotopes, D%Density
        Else
            Read ( unit=LU, fmt=*, iostat=IOSTAT, iomsg=IOMSG ) D%Name, D%Num_Isotopes, D%Density
        End If bin1
R1err:  If (IOSTAT .ne. 0) Then
            Write (*,'(a,i0,1x,a)') 'Constant Line Read Error, IOSTAT = ', IOSTAT, trim(IOMSG)
            Stop 'Abort Read_Target_Material'
        End If R1err
!
!**********************************************************************************************************************************
! Allocate Arrays
!**********************************************************************************************************************************
!
        Allocate ( D%A_Target_Material_p(1:D%Num_Isotopes), D%Z_Target_Material_p(1:D%Num_Isotopes), D%D_Target_Material_p(1:D%Num_Isotopes) )
!
!**********************************************************************************************************************************
! Read the data
!**********************************************************************************************************************************
!
        Do i = 1, D%Num_Isotopes
bin2:       If (Binary) Then
                Read ( unit=LU,        iostat=IOSTAT, iomsg=IOMSG ) D%A_Target_Material_p(i), D%Z_Target_Material_p(i), D%D_Target_Material_p(i)
            Else
                Read ( unit=LU, fmt=*, iostat=IOSTAT, iomsg=IOMSG ) D%A_Target_Material_p(i), D%Z_Target_Material_p(i), D%D_Target_Material_p(i)
            End If bin2
        End Do
R2err:  If (IOSTAT .ne. 0) Then
            Write (*,'(a,i0,1x,a)') 'Target Data Read Error, IOSTAT = ', IOSTAT, trim(IOMSG)
            Stop 'Abort Read_Target_Material'
        End If R2err
!
!**********************************************************************************************************************************
! Return to calling programs
!**********************************************************************************************************************************
!
        Return
!
!**********************************************************************************************************************************
! End of Subroutine
!**********************************************************************************************************************************
!
    End Subroutine Read_Target_Material
Call graph
read_data calls read_target_material
read_tm calls read_data
read_trninput calls read_data
hzetrn_trn calls read_tm, read_trninput