Output_Bytes – quarantine
Output_Bytes Function
40 statements
Source File
private function Output_Bytes(Read_Flag, FILE, Binary, Dimen, lower, upper) result(OBytes)
No implicit typing
FILE - The file name just read/written Read_Flag - .true. if reading; .false. if writting Binary - .true if binary and .false. if ASCII Dimen - The dimension of the array being read/written lower - The lower bounds of the array indicies upper - The upper bounds of the array indicies OBytes - The number of BYTES read/written to/from a file (needs to be I*8)
Determine the size in Bytes of an ASCII data file
End of IF block on data size determination
Set the function result to an integer of size - use default fortran 2003 conversion This is in BYTES
Find the 1024 byte scale that brings the size between >=1 and <1024 then set unit to the two letter code for the scale factor
Tell the user - whether a read or write
Return to calling program
End of function Output_Bytes
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: Read_Flag
character(len=*), intent(in) :: FILE
logical, intent(in) :: Binary
integer, intent(in) :: Dimen
integer, intent(in) :: lower(1:Dimen)
integer, intent(in) :: upper(1:Dimen)
Return Value integer
Local Varaibles Data_size - The size in B/kB/MB/GB/TB of the data unit - The unit used in the write statement punit - The possible sizes allowed i - Do loop index
Called by
Contents
Source Code
Output_Bytes
Source Code
    Function Output_Bytes ( Read_flag, FILE, Binary, Dimen, lower, upper ) Result ( OBytes )
!
!**********************************************************************************************************************************
! No implicit typing
!**********************************************************************************************************************************
!
        Implicit None
!
!**********************************************************************************************************************************
! FILE - The file name just read/written
! Read_Flag - .true. if reading; .false. if writting
! Binary - .true if binary and .false. if ASCII
! Dimen - The dimension of the array being read/written
! lower - The lower bounds of the array indicies
! upper - The upper bounds of the array indicies
! OBytes - The number of BYTES read/written to/from a file (needs to be I*8)
!**********************************************************************************************************************************
!
        Character(Len=*), intent(in) :: FILE
        Logical, intent(in) :: Read_Flag, Binary
        Integer, intent(in) :: Dimen, lower(1:Dimen), upper(1:Dimen)
        Integer :: OBytes
!
!**********************************************************************************************************************************
! Local Varaibles
!   Data_size - The size in B/kB/MB/GB/TB of the data
!   unit - The unit used in the write statement
!   punit - The possible sizes allowed
!   i - Do loop index
!**********************************************************************************************************************************
!
        Real :: Data_size
        Character(Len=2) :: unit, punit(5) = [ 'B ', 'kB', 'MB', 'GB', 'TB' ]
        Integer :: i
!
!**********************************************************************************************************************************
! Determine the size in Bytes of a binary data file
!**********************************************************************************************************************************
!
IFBin:  If (Binary) Then
            Data_size = 1.0d0
DoBsize:    Do i = 1, Dimen
                Data_size = Data_size * ( upper(i)-lower(i)+1 )
            End Do DoBSize
            Data_size = Data_size * kind(Data_size)
            Data_size = Data_size + ( 2*Dimen*kind(upper(1)) )
!
!**********************************************************************************************************************************
! Determine the size in Bytes of an ASCII data file
!**********************************************************************************************************************************
!
        Else
            Data_size = 1.0d0
DoAsize:    Do i = 1, Dimen
                Data_size = Data_size * ( upper(i)-lower(i)+1 )
            End Do DoASize
            Data_size = Data_size * ASCII_DATA_SIZE
            Data_size = Data_size + ( 2*Dimen*ASCII_BOUND_SIZE )
!
!**********************************************************************************************************************************
! End of IF block on data size determination
!**********************************************************************************************************************************
!
        End If IFBin
!
!**********************************************************************************************************************************
! Set the function result to an integer of size - use default fortran 2003 conversion
!   This is in BYTES
!**********************************************************************************************************************************
!
        OBytes = Int ( Data_size )
!
!**********************************************************************************************************************************
! Find the 1024 byte scale that brings the size between >=1 and <1024 then set unit to the two letter code for the scale factor
!**********************************************************************************************************************************
!
        unit = 'ER'
Dounit: Do i = 1, 5
            If ( Data_size .ge. 1.0d0  .and.  Data_size .lt. 1024.0d0 ) Then
                unit = punit(i)
                exit
            End If
            Data_size = Data_size / 1024.0d0
        End Do Dounit
!
!**********************************************************************************************************************************
! Tell the user - whether a read or write
!**********************************************************************************************************************************
!
IfRDF:  If (Read_flag) Then
            Write (*,'(1x,f14.7,1x,a2,a,a)') Data_size, unit, ' read from ', trim(FILE)
        Else
            Write (*,'(1x,f14.7,1x,a2,a,a)') Data_size, unit, ' written to ', trim(FILE)
        End If IfRDF
!
!**********************************************************************************************************************************
! Return to calling program
!**********************************************************************************************************************************
!
        Return
!
!**********************************************************************************************************************************
! End of function Output_Bytes
!**********************************************************************************************************************************
!
    End Function Output_Bytes
Call graph
read_data calls output_bytes
read_tm calls read_data
read_trninput calls read_data
hzetrn_trn calls read_tm, read_trninput