Read_Data – quarantine
Read_Data Subroutine
75 statements
Source File
public subroutine Read_Data(FILE, Data_up, ACCESS, OBytes, Opt_Int, Quite)
Uses
Type_CArray_1D_Mod
Type_Target_Material_Mod
This routine reads data into the data type passed by Data_up and passes it back to the calling routine. The data type is queried below and the proper set of reads are used. Any data type can be read with this routine.
Use needed modules for data definitions
No implicit data typing
Data_up - An unlimited polymorphic Pointer that points to the data straucture to be read FILE - The file name to open and connect to the LU ACCESS - Optional value of BIN or ASC to open the file formatted ro unformatted manually. The default is in the global variable G_Binary OBytes - Optional output for the output number of bytes read Opt_Int - Optional Integer to pass to type routine Quite - Optional Integer argument to not have data read output if defined, value unimportant
Determine access for file open (formatted or unformatted)
Open the data file for read
Select code execution on the data type being read
Type: CArray_1D - read data and tell user how many bytes read
Type Target_Material - read data
Class Default - Error out
End Select Type on Data_up
Close the Data File
Return to the calling program
End of Subroutine Read_Data
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: FILE
class(*), intent(in), Pointer :: Data_up
character(len=3), intent(in), optional :: ACCESS
integer, intent(out), optional :: OBytes
integer, intent(inout), optional :: Opt_Int
integer, intent(in), optional :: Quite
Local variables i - do loop index LU - The Logical Unit number to read IOSTAT - Message buffer from IO errors NOBytes - The function to determine BYTES read IOMSG - Message buffer from memory managment errors NAM - Return from Inquire Function that contains the name of the opened data file FORM - The string used to open the file formatted or unformatted Binary - Flag for Binary (unformatted - true) or ASCII (formatted - false) data access OPENED - Flag for opened data file or not from the Inquire function RW - Flag to determine if reading or writting to Output_Bytes
Calls
Called by
Contents
Source Code
Read_Data
Source Code
    Subroutine Read_Data ( FILE, Data_up, ACCESS, OBytes, Opt_Int, Quite )
!
!**********************************************************************************************************************************
! This routine reads data into the data type passed by Data_up and passes it back to the calling routine.
!       The data type is queried below and the proper set of reads are used.
!       Any data type can be read with this routine.
!**********************************************************************************************************************************
! Use needed modules for data definitions
!**********************************************************************************************************************************
!
      Use Type_CArray_1D_Mod
      Use Type_Target_Material_Mod
!
!**********************************************************************************************************************************
! No implicit data typing
!**********************************************************************************************************************************
!
        Implicit None
!
!**********************************************************************************************************************************
! Data_up - An unlimited polymorphic Pointer that points to the data straucture to be read
! FILE - The file name to open and connect to the LU
! ACCESS - Optional value of BIN or ASC to open the file formatted ro unformatted manually.
!               The default is in the global variable G_Binary
! OBytes - Optional output for the output number of bytes read
! Opt_Int - Optional Integer to pass to type routine
! Quite - Optional Integer argument to not have data read output if defined, value unimportant
!**********************************************************************************************************************************
!
        Class(*), Pointer,          intent(in)    :: Data_up
        Character(Len=*),           intent(in)    :: FILE
        Character(Len=3), Optional, intent(in)    :: ACCESS
        Integer, Optional,          intent(out)   :: OBytes
        Integer, Optional,          intent(inout) :: Opt_Int
        Integer, Optional,          intent(in)    :: Quite
!
!**********************************************************************************************************************************
! Local variables
!   i - do loop index
!   LU - The Logical Unit number to read
!   IOSTAT - Message buffer from IO errors
!   NOBytes - The function to determine BYTES read
!   IOMSG - Message buffer from memory managment errors
!   NAM - Return from Inquire Function that contains the name of the opened data file
!   FORM - The string used to open the file formatted or unformatted
!   Binary - Flag for Binary (unformatted - true) or ASCII (formatted - false) data access
!   OPENED - Flag for opened data file or not from the Inquire function
!   RW - Flag to determine if reading or writting to Output_Bytes
!**********************************************************************************************************************************
!
        Integer                   :: i, LU, IOSTAT
        Integer                   :: NOBytes
        Character(LEN=IOMSG_SIZE) :: IOMSG
        Character(LEN=CLEN_SIZE)  :: NAM
        Character(LEN=11)         :: FORM
        Logical                   :: Speak, Binary, OPENED, RW = .true.
!
!**********************************************************************************************************************************
! Determine if Quite is defined
!**********************************************************************************************************************************
!
        Speak = .true.
Q:      If (Present(Quite)) Then
           Speak = .false.
        End If Q
!
!**********************************************************************************************************************************
! Determine access for file open (formatted or unformatted)
!**********************************************************************************************************************************
!
DACif:  If (.not. Present(ACCESS)) Then
            Binary = G_BINARY
BINIf:      If (Binary) Then
                FORM = 'unformatted'
            Else
                FORM = 'formatted'
            End If BINIf
        Else
ACif:       If (ACCESS(1:3) .eq. 'BIN') Then
                FORM = 'unformatted' ; Binary = .true.
            Else If ( ACCESS(1:3) .eq. 'ASC' ) Then
                FORM = 'formatted' ; Binary = .false.
            Else
                Write (*,*) 'Optional ACCESS present does not equal "BIN" or "ASC"'
                Write (*,*) 'ACCESS = ', ACCESS(1:3)
                Stop 'Abort Read_Data'
            End If ACif
        End If DACif
!
!**********************************************************************************************************************************
! Open the data file for read
!**********************************************************************************************************************************
!
        Open ( newunit=LU, file=trim(FILE), status='old', form=trim(FORM), action='read', iostat=IOSTAT, iomsg=IOMSG )
OPerr:  If (IOSTAT .ne. 0) Then
            Write (*,'(a,i0,1x,a)') 'File Open Error, IOSTAT = ', IOSTAT, trim(IOMSG)
            Stop 'Abort Read_Data'
        End If OPerr
!
!**********************************************************************************************************************************
! Select code execution on the data type being read
!**********************************************************************************************************************************
!
DUPtyp: Select Type (Data_up)
!
!**********************************************************************************************************************************
! Type: CArray_1D - read data and tell user how many bytes read
!**********************************************************************************************************************************
!
            Type is ( CArray_1D )
!
                Call Read_CArray_1D ( LU, Binary, Data_up )
Q_C1D:          If (Speak) Then
WObytes_C1D:        If (present(OBytes)) Then
!                        OBytes = Output_Bytes (RW, FILE, Binary, Data_up%Dimen, Data_up%lower_p, Data_up%upper_p)
                        OBytes = Output_Bytes ( RW, FILE, Binary, Data_up%Dimen, Data_up%lower, Data_up%upper )
                    Else
!                        NObytes = Output_Bytes (RW, FILE, Binary, Data_up%Dimen, Data_up%lower_p, Data_up%upper_p)
                        NObytes = Output_Bytes ( RW, FILE, Binary, Data_up%Dimen, Data_up%lower, Data_up%upper )
                    End If WOBytes_C1D
                End If Q_C1D
print *, 'Read_Write_Basic_Mod: Data_up%upper(1) = ', Data_up%upper(1)
do i = 1, Data_up%upper(1)
print *, '                      Data_up%Data(i)  = ', i, trim(Data_up%Data(i))
enddo
!
!**********************************************************************************************************************************
! Type Target_Material - read data
!**********************************************************************************************************************************
!
            Type is ( Target_Material_Pointer )
!
                Call Read_Target_Material ( LU, Binary, Data_up )
Q_Targ:         If (Speak) Then
                    Write (*,*) 'Read ', trim(FILE), ' - no size data available'
                End If Q_Targ
!
!
!**********************************************************************************************************************************
! Class Default - Error out
!**********************************************************************************************************************************
!
            Class Default
!
                Write (*,'(a,i0,1x,a)') 'The class of the data passed to Read_Data was not recognized'
                Stop 'Abort Read_Data'
!
!**********************************************************************************************************************************
! End Select Type on Data_up
!**********************************************************************************************************************************
!
        End Select DUPTyp
!
!**********************************************************************************************************************************
! Close the Data File
!**********************************************************************************************************************************
!
        Close ( unit=LU, iostat=IOSTAT, iomsg=IOMSG )
CLerr:  If (IOSTAT .ne. 0) Then
            Write (*,'(a,i0,1x,a)') 'File Close Error, IOSTAT = ', IOSTAT, trim(IOMSG)
            Stop 'Abort Read_Data'
        End If CLerr
!
!**********************************************************************************************************************************
! Return to the calling program
!**********************************************************************************************************************************
!
        Return
!
!**********************************************************************************************************************************
! End of Subroutine Read_Data
!**********************************************************************************************************************************
!
    End Subroutine Read_Data
Call graph
read_data calls read_target_material, output_bytes, read_carray_1d
read_tm calls read_data
read_trninput calls read_data
hzetrn_trn calls read_tm, read_trninput